import logging
import string
import fileinput


def convertDifficulties():

	result = {}

	for line in fileinput.input():
		line = string.lstrip(line)
		if len(line) == 0:
			continue
		if line[0] != "+" and line[0] != "-":
			#All lines we're looking for start with either + or -
			continue
		negative = line[0] == "-"
		line = string.lstrip(line[1:])
		parts = line.split(" * ")
		if len(parts) > 2:
			logging.error("Skipped line " + line + " because it was not shaped the way we expected.")
		
		if len(parts) == 1:
			name = "Constant"
		else:
			name = string.strip(parts[1])

		if negative:
			parts[0] = "-" + parts[0]

		result[name] = float(parts[0])

	print("//auto-generated by difficulty-convert.py DO NOT EDIT")
	print("package sudoku")
	print("func init() {")

	print("\tdifficultySignalWeights = map[string]float64{")

	for key,val in result.items():
		print("\t\t\"" + key + "\" : " + str(val) + ",")

	print("\t}")
	print("}")



convertDifficulties()