// generated by stringer -type=Phase; DO NOT EDIT

package main

import "fmt"

const _Phase_name = "DifficultiesSolvesWekaHistogram"

var _Phase_index = [...]uint8{0, 12, 18, 22, 31}

func (i Phase) String() string {
	if i < 0 || i+1 >= Phase(len(_Phase_index)) {
		return fmt.Sprintf("Phase(%d)", i)
	}
	return _Phase_name[_Phase_index[i]:_Phase_index[i+1]]
}
